server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 496139560764-npsodl65ubpuglr805vauc69d5n3tdsk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/tuyendung_tts
    username: root
    password: 1234
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ba882863777110
    password: ca666416ccafcb
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true