DROP
DATABASE IF EXISTS tuyendung_tts;
CREATE
DATABASE tuyendung_tts;
USE
tuyendung_tts;

CREATE TABLE TAIKHOAN
(
    maTaiKhoan VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    matKhau VARCHAR(255),
    vaiTro ENUM ('SINH_VIEN','NHA_TRUONG','NHA_TUYEN_DUNG','ADMIN'),
    trangThai ENUM ('KHONG_HOAT_DONG','HOAT_DONG'),
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE NHATRUONG
(
    maNhaTruong VARCHAR(255) PRIMARY KEY,
    maTaiKhoan VARCHAR(255),
    tenTruong VARCHAR(255),
    diaChi VARCHAR(255),
    soDienThoai VARCHAR(12) UNIQUE,
    maSoThue VARCHAR(50) UNIQUE,
    bieuTuong VARCHAR(255),
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maTaiKhoan) REFERENCES TAIKHOAN (maTaiKhoan)
);

CREATE TABLE DOANHNGHIEP
(
    maDoanhNghiep VARCHAR(255) PRIMARY KEY,
    maTaiKhoan VARCHAR(255),
    tenDoanhNghiep VARCHAR(255),
    moHinh VARCHAR(255),
    linhVuc VARCHAR(255),
    diaChi VARCHAR(255),
    soDienThoai VARCHAR(12) UNIQUE,
    maSoThue VARCHAR(50) UNIQUE,
    trangDoanhNghiep VARCHAR(255),
    anhDaiDien VARCHAR(255),
    moTa TEXT,
    phucLoi TEXT,
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maTaiKhoan) REFERENCES TAIKHOAN (maTaiKhoan)
);

CREATE TABLE SINHVIEN
(
    maSinhVien VARCHAR(255) PRIMARY KEY,
    maTaiKhoan VARCHAR(255),
    maNhaTruong VARCHAR(255),
    hoVaTen VARCHAR(255),
    ngaySinh DATE,
    soDienThoai VARCHAR(12) UNIQUE,
    gioiTinh ENUM('NU','NAM'),
    diaChi VARCHAR(255),
    khoa VARCHAR(255),
    lop VARCHAR(255),
    chuyenNganh VARCHAR(255),
    CCCD VARCHAR(16),
    trangThai ENUM('SAI','DUNG'),
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maTaiKhoan) REFERENCES TAIKHOAN (maTaiKhoan),
    FOREIGN KEY (maNhaTruong) REFERENCES NHATRUONG (maNhaTruong)
);

CREATE TABLE DANHMUC
(
    maDanhMuc VARCHAR(255) PRIMARY KEY,
    tenDanhMuc VARCHAR(255),
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE KYNANG
(
    maKyNang VARCHAR(255) PRIMARY KEY,
    maDanhMuc VARCHAR(255),
    tenKyNang VARCHAR(255),
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maDanhMuc) REFERENCES DANHMUC (maDanhMuc)
);

CREATE TABLE BAIDANG
(
    maBaiDang VARCHAR(255) PRIMARY KEY,
    maDoanhNghiep VARCHAR(255),
    maDanhMuc VARCHAR(255),
    tieuDe VARCHAR(255),
    diaChi VARCHAR(255),
    yeuCau TEXT,
    moTa TEXT,
    denHan DATETIME,
    quyenLoi TEXT,
    loai ENUM('BAN_THOI_GIAN','TOAN_THOI_GIAN'),
    trangThai ENUM('HET_HAN','CON_HAN'), -- 0: Het Han, 1: Con
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maDoanhNghiep) REFERENCES DOANHNGHIEP (maDoanhNghiep),
    FOREIGN KEY (maDanhMuc) REFERENCES DANHMUC (maDanhMuc)
);
CREATE TABLE KYNANG_BAIDANG
(
    maKyNang VARCHAR(255),
    maBaiDang VARCHAR(255),
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maKyNang) REFERENCES KYNANG (maKyNang),
    FOREIGN KEY (maBaiDang) REFERENCES BAIDANG (maBaiDang),
    PRIMARY KEY (maKyNang, maBaiDang)
);

CREATE TABLE SINHVIEN_BAIDANG
(
    maSVBD VARCHAR(255) PRIMARY KEY,
    maSinhVien VARCHAR(255),
    maBaiDang VARCHAR(255),
    hoVaten VARCHAR(255),
    soDienThoai VARCHAR(255),
    email VARCHAR(255),
    soYeuLyLich VARCHAR(255),
    ketQua ENUM('TU_CHOI','THONG_QUA','DANG_CHO'),
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maSinhVien) REFERENCES SINHVIEN (maSinhVien),
    FOREIGN KEY (maBaiDang) REFERENCES BAIDANG (maBaiDang)
);

CREATE TABLE LICHPHONGVAN
(
    maLichPhongVan VARCHAR(255) PRIMARY KEY,
    maSinhVien VARCHAR(255),
    maDoanhNghiep VARCHAR(255),
    viTriPhongVan VARCHAR(255),
    ngayPhongVan DATETIME,
    diaDiem VARCHAR(255),
    hinhThucPhongVan ENUM('TRUC_TIEP','TRUC_TUYEN'),
    trangThai ENUM('TU_CHOI','DONG_Y','DANG_CHO'),
    hanXacNhan DATETIME,
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maSinhVien) REFERENCES SINHVIEN (maSinhVien),
    FOREIGN KEY (maDoanhNghiep) REFERENCES DOANHNGHIEP (maDoanhNghiep)
);

CREATE TABLE LOIMOITHUCTAP
(
    maLMTT VARCHAR(255) PRIMARY KEY,
    maSinhVien VARCHAR(255),
    maDoanhNghiep VARCHAR(255),
    viTriThucTap VARCHAR(255),
    tuNgay DATE,
    denNgay DATE,
    diaChi VARCHAR(255),
    loaiThucTap ENUM('HET_HAN','CON_HAN'),
    quyenLoi TEXT,
    trangThai ENUM('TU_CHOI','CHAP_NHAN','DANG_CHO'),
    hanXacNhan DATETIME,
    taoVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP,
    capNhatVaoLuc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (maSinhVien) REFERENCES SINHVIEN (maSinhVien),
    FOREIGN KEY (maDoanhNghiep) REFERENCES DOANHNGHIEP (maDoanhNghiep)
);



